core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

sadio_auth:
    resource: "@SadioAuthBundle/Resources/config/routing.yml"
    prefix:   /user/

sadio_jobs_plateform:
    resource: "@SadioJobsPlateformBundle/Resources/config/routing.yml"
    prefix:   /platform/
