sadio_auth:
    resource: "@SadioAuthBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

sadio_anti_spam:
    resource: "@SadioAntiSpamBundle/Resources/config/routing.yml"
    prefix:   /antispam/

sadio_jobs_plateform:
    resource: "@SadioJobsPlateformBundle/Resources/config/routing.yml"
    prefix:   /platform/
