<?php

namespace Sadio\JobsPlateformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * OfferRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    // Permet de récupérer une Offre avec ses catégories => quand on fait offer.getCategories, 
    // Pas de requetes SQL supplémentaire déclenchée
    public function findOneWithAllRelations($offerSlug) 
    {
        // "o" represente l'alias de Offer, "c" celui de Category et "u" celui de User
        $qb = $this->createQueryBuilder('o');

        // On ajoute d'abord Category
        $qb->leftJoin('o.categories', 'c')
           ->addSelect('c')

        // On ajoute ensuite User
           ->leftJoin('o.user', 'u')
           ->addSelect('u')

        // Enfin on met la condition
           ->where('o.slug = :slug')
           ->setParameter('slug', $offerSlug);
        
        return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
        // return $qb->getQuery()->getSingleResult(); meme chose que la méthode en haut renvoie un objet
        // Mais si la méthode ne trouve rien => elle déclenche une erreur 
        // => a éviter si on veut délcencher soit même une erreur 404
    }
    // Permet de récupérer une Offre avec ses catégories => quand on fait offer.getCategories dans TWIG, 
    // Pas de requetes SQL supplémentaire déclenchée
    public function findAllWithUser($page, $offersPerPage) 
    {
        // "o" represente l'alias de Offer et "u" celui de User
        $qb = $this->createQueryBuilder('o');

        $qb->innerJoin('o.user', 'u')
           ->addSelect('u')
           ->orderBy('o.id', 'DESC');
        
        // On définit l'annonce à partir de laquelle commencer la liste
        // Ainsi que le nombre d'annonce à afficher sur une page
        $qb->setFirstResult(($page-1) * $offersPerPage)
           ->setMaxResults($offersPerPage);

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($qb, true);
    }
}
