# Prefix /platform/
# Page d'Accueil
sadioJobsP_homepage:
    path:     /{page}
    defaults: 
        _controller: SadioJobsPlateformBundle:Default:index
        page: 1
    requirements:
        page: \d*

# Page Single Post
sadioJobsP_singlePost:
    path:     /offer/{slug}
    defaults: 
        _controller: SadioJobsPlateformBundle:Default:view

# Page Add New Post
sadioJobsP_newPost:
    path:     /new-offer
    defaults: 
        _controller: SadioJobsPlateformBundle:Default:new

# Page Update Post
sadioJobsP_editPost:
    path:     /edit-offer/{slug}
    defaults: 
        _controller: SadioJobsPlateformBundle:Default:edit

# Page Delete Post
sadioJobsP_deletePost:
    path:     /delete-offer/{id}
    defaults: 
        _controller: SadioJobsPlateformBundle:Default:delete
    requirements:
        id: \d+
